### ISSUE TITLE
issue: 쿠폰 관리 화면(View Data) API 개발

### ISSUE THREAD

**Issue by matrixpower1004** [Upjuyanolja/Upjuyanolja_BE#109]
### 💬Description
쿠폰 관리 화면을 구성할 데이터를 View에 응답하는 API를 개발한다.

### 📜Todo
- [x] 쿠폰 관리 화면(View Data) API 구현
- [x] 테스트 코드 작성
- [x] REST Docs 문서 작성
