### ISSUE TITLE
issue: 숙소, 객실 등록 시 에러 처리 추가 개발

### ISSUE THREAD

**Issue by JeongUijeong** [Upjuyanolja/Upjuyanolja_BE#114]
### 💬Description
숙소, 객실 등록 시 추가적인 에러 처리가 필요합니다. 

<추가로 에러 처리할 상황>
- 숙소 이미지가 하나도 없을 경우
- 객실이 하나도 없을 경우
- 객실 이미지가 하나도 없을 경우

### 📜Todo
- [x] 숙소 이미지가 하나도 없을 경우 에러 처리
- [x] 객실이 하나도 없을 경우 에러 처리
- [x] 객실 이미지가 하나도 없을 경우 에러 처리
