### ISSUE TITLE
issue: 쿠폰 추가 구매 API 개발

### ISSUE THREAD

**Issue by matrixpower1004** [Upjuyanolja/Upjuyanolja_BE#119]
### 💬Description
- 쿠폰 추가 구매 API 기능 구현

### 📜Todo
- [x] 쿠폰 추가 구매 API 구현
- [x] 테스트 코드 작성
- [x] REST Doc 작성
