### ISSUE TITLE
issue: 회원 가입 관련 기능을 수정

### ISSUE THREAD

**Issue by JeongUijeong** [Upjuyanolja/Upjuyanolja_BE#129]
### 💬Description
현재 구현되어 있는 내용 중 수정해야 할 부분이 있습니다. 

- 이메일 중복 검사에서 password를 요구하지 않도록 DTO 따로 생성
  - 이메일 중복 검사 API 요청 시 비밀번호도 함께 받고 Validation도 하기 때문에 이메일만 담아서 요청을 보내면 INVALID_REQUEST_BODY가 발생합니다. 
- 비밀번호 정규표현식 수정
  - 현재: "^(?=.*[A-Za-z])(?=.*\\d)(?=.*[~!@#$%^&*()+|=])[A-Za-z\\d~!@#$%^&*()+|=]{8,20}$"
  - 수정: "/^(?=.[a-zA-Z])(?=.\d).{8,20}$/"
- 회원 가입 시 휴대폰 번호 받지 않도록 수정
  - 휴대폰 번호는 입점 DB에서 가져오도록 합니다. 
- 이메일 인증 번호 요청 시 이메일 중복 여부 검사 추가
  - 중복된 이메일 경우 DUPLICATED_EMAIL 예외를 던지도록 합니다. 

### 📜Todo
- [x] 이메일 중복 검사 DTO 생성
- [x] 비밀번호 정규표현식 수정
- [x] 휴대폰 번호는 입점 DB에서 가져오도록 수정
- [x] 이메일 인증 번호 요청 시 이메일 중복 여부 검사 추가

### 🫱🏻‍🫲🏻ETC
@chadongmin 
동민님이 구현하신 내용입니다만, 빠르게 수정이 필요한 것 같은데 오늘 내로 수정이 가능하실까요?? 🥹
