### ISSUE TITLE
issue: 예약 도메인 엔티티 수정

### ISSUE THREAD

**Issue by matrixpower1004** [Upjuyanolja/Upjuyanolja_BE#13]
### 💬Description
예약 도메인의 ERD를 검토하고 ERD와 엔티티를 수정한다.

### 📜Todo
- [x] Docker에 Maria DB 설치 및 설정
- [x] 예약 관련 ERD 검토 및 수정
- [x] Entity 수정
- [x] 예약 도메인 더미 데이터 SQL 작성
- [x] 결제 도메인 엔티티 생성. Payment.java

### 🫱🏻‍🫲🏻ETC
- 현재 Member Entity 및 Spring Security 가 존재하지 않아 임의로 mock member 생성 후 진행
- 차후 Security 로직 완료되면 PrincipalDetails 에서 유저 정보를 가져오도록 수정할 예정.
