### ISSUE TITLE
issue: 쿠폰 수정 및 삭제 API 개발

### ISSUE THREAD

**Issue by matrixpower1004** [Upjuyanolja/Upjuyanolja_BE#135]
### 💬Description
쿠폰의 상태를 수정할 수 있다.
쿠폰을 삭제 할 수 있다.

### 📜Todo
- [x] 쿠폰 수정 및 삭제 API  구현
- [x] 쿠폰 수정 및 삭제 Test 작성
- [x] 쿠폰 수정 및 삭제 REST Docs  작성
