### ISSUE TITLE
issue: 쿠폰 현황 통계 API 개발

### ISSUE THREAD

**Issue by matrixpower1004** [Upjuyanolja/Upjuyanolja_BE#136]
### 💬Description
- 쿠폰 현황 통계 API를 개발한다. 

### 📜Todo
- [ ] 쿠폰 발급 내역 Entity 및 Repository 작성
- [ ] 쿠폰 현황 통계 API 구현
- [ ] 쿠폰 현황 통계 테스트 작성
- [ ] 쿠폰 현황 통계 REST Docs 작성
