### ISSUE TITLE
issue: 일자별 매출 통계 API 개발

### ISSUE THREAD

**Issue by matrixpower1004** [Upjuyanolja/Upjuyanolja_BE#138]
### 💬Description
일자별 매출 통계 API를 개발한다. 

### 📜Todo
- [x] 일자별 매출 통계 쿼리 작성 및 테스트
- [x] 일자별 매출 통계 API 구현 
- [x] 일자별 매출 통계 API 테스트 작성
- [x] 일자별 매출 통계 REST Docs 작성
