### ISSUE TITLE
issue: API Response Format 리팩토링 

### ISSUE THREAD

**Issue by chaewon12** [Upjuyanolja/Upjuyanolja_BE#144]
### 💬Description
중간 피드백에서 받은 피드백을 반영하여 응답 바디, 헤더 형식을 수정한다. 

### 📜Todo
- [ ] APIResponse.success 제거 
- [ ] APIResponse.FailResponse Exception 수정 
- [ ] RestDocs 헤더에서 필요없는 필드 제거 

### 🫱🏻‍🫲🏻ETC
![image](https://github.com/Upjuyanolja/Upjuyanolja_BE/assets/65496092/49dd7cf5-a649-4b46-9a0b-08174d4af0f1)
![image](https://github.com/Upjuyanolja/Upjuyanolja_BE/assets/65496092/a4cee90a-825d-4d16-b117-ea179357dc87)

![image](https://github.com/Upjuyanolja/Upjuyanolja_BE/assets/65496092/3a9516d2-72ed-40f4-b624-d813421dd160)
