### ISSUE TITLE
issue: 숙소 등록, 객실 등록 버그 발생

### ISSUE THREAD

**Issue by JeongUijeong** [Upjuyanolja/Upjuyanolja_BE#153]
### 💬Description
숙소 등록, 객실 등록 시 이미지 저장에 버그가 발견됐습니다. 

---
1. 숙소 등록 시 객실 등록이 안된다. 
  - 객실 등록 시 숙소를 저장하지 않아, 해당 숙소 소속으로 저장되지 않음
  - 저장할 객실 Entity를 만드는 빌더에서 숙소도 지정하면 해결될 것으로 예상됨
---
2. 숙소 등록 시 이미지 등록이 안된다. 
  - 숙소에 객실 등록 후 Entity를 Refresh하지 않아 등록된 이미지가 응답 json에서는 보이지 않음
  - Entity를 Refresh하면 해결될 것으로 예상됨
---
3. 객실 등록 후 숙소 객실 목록 조회 시 검색되지 않는다. 
  - 숙소 등록 시 객실 등록이 안되던 문제와 같은 문제로, 숙소 지정 시 해결될 것으로 예상됨
---
4. 객실 이름 중복 검사 시 모든 객실에 대해 검사한다. 
  - 해당 객실이 속한 숙소 내부의 객실 중에서만 검사하도록 수정하면 해결될 것으로 예상됨

### 📜Todo
- [x] 객실 Entity 생성 시 숙소 지정 추가
- [x] 숙소, 객실 Entity refresh 추가
- [x] 객실 이름 중복 검사 시 해당 객실이 속한 숙소 내부의 객실 중에서만 검사하도록 수정
