### ISSUE TITLE
issue: fix: 비즈니스 요구 사항에 맞지 않는 에러 코드 응답 수정

### ISSUE THREAD

**Issue by matrixpower1004** [Upjuyanolja/Upjuyanolja_BE#171]
### 💬Description
- Request Dto에 있던 `@Min`  애너테이션을 삭제.

### 📜Todo
- [x] Request Dto에 있던 `@Min`  애너테이션을 삭제.
- [x] point 엔티티 변경에 따른 코드 수정
- [x] 쿠폰 만들기 request dto의 포인트 필드의 타입을 long으로 변경.
- [x] 쿠폰 수정 및 쿠폰 삭제 시 영속성 컨텍스트를 이용하여 저장하던 로직을 명시적으로 저장하도록 코드 수정. 
- [x] 빈 import 정리

### 🫱🏻‍🫲🏻ETC
기타사항
