### ISSUE TITLE
issue: 삭제된 객실도 쿠폰 만들기에서 조회되는 버그 발생

### ISSUE THREAD

**Issue by matrixpower1004** [Upjuyanolja/Upjuyanolja_BE#209]
### 💬Description
- 객실 조회시 deleted_at 체크를 하지 않아 삭제된 객실도 쿠폰 만들기에서 조회되는 버그가 발생
- 쿠폰 관리에서도 삭제된 객실이 조회되는 버그가 발생

### 📜Todo
- [x] 쿼리에 숙소 및 객실의 삭제 상태를 체크하는 로직 추가.
- [x] 쿠폰 삭제 상태 체크로 마찬가지로 쿼리에서 체크하도록 수정.
- [x] 쿠폰 삭제 상태 체크를 팀 코드에 맞춰서 기존의 Enum에서 DELETED로 체크하던 것을 deleted_at 컬럼의 null 여부로 체크하도록 로직 변경
- [x] 로직 변경에 영향을 받은 테스트 코드 수정

### 🫱🏻‍🫲🏻ETC
- 리뷰 부탁 드립니다.
