### ISSUE TITLE
issue: 숙소, 객실 기능 코드 리팩토링

### ISSUE THREAD

**Issue by JeongUijeong** [Upjuyanolja/Upjuyanolja_BE#228]
### 💬Description
숙소, 객실 기능 코드를 리팩토링해야 합니다. 
다음을 고려합니다. 

1. 로직 개선
2. 의존성 최소화
3. 메서드, 조건문 정리
4. 가독성 개선
5. 네이밍 수정

### 📜Todo
- [x] 숙소 기능 코드 리팩토링, 클린 코드 적용
- [x] 객실 기능 코드 리팩토링, 클린 코드 적용
- [x] 테스트 코드 추가 및 수정 보완
