### ISSUE TITLE
issue: Spring REST Docs 세팅

### ISSUE THREAD

**Issue by JeongUijeong** [Upjuyanolja/Upjuyanolja_BE#27]
### 💬Description
API 문서화에 Spring REST Docs를 활용하기로 정했습니다. 
이를 위해 테스트 코드와 문서 작성의 편의성과 효율을 위해 관련 세팅을 해야 합니다. 

필요한 세팅은 다음과 같습니다. 

1. snippet template 추가
2. REST Docs 환경 설정
3. REST Docs Support Class 구현
4. index.adoc 파일 작성

### 📜Todo
- [x] snippet template 추가
- [x] REST Docs 환경 설정
- [x] REST Docs Support Class 구현
- [x] index.adoc 파일 작성
