### ISSUE TITLE
issue: 전체 Entity 생성

### ISSUE THREAD

**Issue by JeongUijeong** [Upjuyanolja/Upjuyanolja_BE#3]
### 💬Description
- 원활한 개발을 위해 우선적으로 전체 Entity와 필요한 Repository를 생성합니다. 
- 중복해서 사용하게 될 생성, 수정, 삭제일이 포함된 BaseTime 엔터티를 생성합니다. 
- 생성 수정 삭제에 대한 JPA Audit 설정을 추가합니다. 

### 📜Todo
- [x] 전체 Entity 생성
- [x] 필요한 Repository 생성
- [x] BaseTime 엔터티 생성
- [x] JPA Audit 설정 추가
