### ISSUE TITLE
issue: 이메일 중복 검사 기능 개발

### ISSUE THREAD

**Issue by JeongUijeong** [Upjuyanolja/Upjuyanolja_BE#34]
### 💬Description
회원 가입 시 이메일 중복 검사를 하기 위해 해당 기능을 구현합니다. 

### 📜Todo
- [x] 이메일 중복 검사 기능 서비스 Logic 구현
- [x] 이메일 중복 검사 API 컨트롤러 구현
- [x] 이메일 중복 검사 Repository 테스트 작성
- [x] 이메일 중복 검사 기능 서비스 단위 테스트 작성
- [x] 이메일 중복 검사 API 컨트롤러 테스트 작성
- [x] 이메일 중복 검사 REST Docs 테스트 작성
- [x] 이메일 중복 검사 adoc 파일 작성
