### ISSUE TITLE
issue: Open API 데이터 수집 수정

### ISSUE THREAD

**Issue by JeongUijeong** [Upjuyanolja/Upjuyanolja_BE#39]
### 💬Description
객실 가격이 0원일 경우 100,000원으로 저장하도록 코드를 수정합니다. 
또한, 객실 수량의 경우 각 객실 타입마다 보유 객실의 수만큼 튜플을 저장하는 방식에서 Stock 테이블을 통해 객실 재고를 관리할 수 있도록 수정합니다. 
객실 재고 관리 방식의 변경으로, 객실 코드가 불필요해졌기 때문에 객실 코드 필드를 삭제합니다. 

### 📜Todo
- [x] 객실 가격 0원일 경우 100,000원으로 저장하도록 코드 수정
- [x] Stock 테이블을 추가하여 객실 재고를 관리하도록 수정
- [x] 객실 코드 필드 삭제

### 🫱🏻‍🫲🏻ETC
insert 문도 새롭게 추출하여 sql 파일 다시 공유 드리도록 하겠습니다!!
