### ISSUE TITLE
issue: PRD 변경에 따른 쿠폰 관련 엔티티 수정

### ISSUE THREAD

**Issue by matrixpower1004** [Upjuyanolja/Upjuyanolja_BE#49]
### 💬Description
PRD 변경에 따라 쿠폰 관련 엔티티를 수정한다.

### 📜Todo
- [x] ERD 수정 반영
- [x] 쿠폰 관련 엔티티 수정
- [x] DiscountType enum에 view에 응답할 쿠폰 이름 만드는 로직, 할인가 반영된 결제 금액 계산하여 반환하는 로직, 할인가 검증 로직(김현아님 코드 재활용)을 응집시킴.
- [x] 각 엔티티의 JpaRepository 생성
