### ISSUE TITLE
issue: 숙소 종류 축소를 적용한 기능 수정

### ISSUE THREAD

**Issue by JeongUijeong** [Upjuyanolja/Upjuyanolja_BE#50]
### 💬Description
기존 숙소 종류(Category)를 모두 사용하지 않기로 기획이 정해졌습니다. 

#### 기존 숙소 종류
- 관광호텔
- 콘도미니엄
- 유스호스텔
- 펜션
- 모텔
- 민박
- 게스트하우스
- 홈스테이
- 서비스드레지던스
- 한옥
- 기타

#### 새로운 숙소 종류
- 호텔/리조트
  - 관광호텔
  - 콘도미니엄
  - 레지던스
- 모텔
  - 모텔
- 펜션/풀빌라
  - 펜션
  - 풀빌라
- 게스트하우스
  - 게스트하우스
  - 한옥

### 📜Todo
- [x] Category enum 수정
- [x] Accommodation Type enum 생성
- [x] Open API 서비스 로직 수정

### 🫱🏻‍🫲🏻ETC
수정된 데이터 다시 INSERT SQL 문 추출하여 공유 드리겠습니다! 😊
