### ISSUE TITLE
issue: 예약/예약 취소 내역 조회  기능 개발

### ISSUE THREAD

**Issue by chaewon12** [Upjuyanolja/Upjuyanolja_BE#59]
### 💬Description
예약/예약 취소 내역 조회  기능 개발

### 📜Todo
- [x] 예약 내역 조회  기능 개발
- [x] 예약 취소 내역 조회 기능 개발
- [x] 테스트 코드 작성 

### 🫱🏻‍🫲🏻ETC
페이징 처리 Default size 정해야함
