### ISSUE TITLE
issue: 보유 숙소 목록 조회 기능 개발

### ISSUE THREAD

**Issue by JeongUijeong** [Upjuyanolja/Upjuyanolja_BE#66]
### 💬Description
업주 회원이 보유 숙소 목록을 조회할 수 있도록 기능을 개발해야 합니다. 

### 📜Todo
- [x] 보유 숙소 목록 조회 기능 구현
- [x] 보유 숙소 목록 조회 테스트 코드 작성
- [x] 보유 숙소 목록 조회 API Docs 작성
