### ISSUE TITLE
issue: 객실 등록 기능 개발

### ISSUE THREAD

**Issue by JeongUijeong** [Upjuyanolja/Upjuyanolja_BE#67]
### 💬Description
업주 회원이 본인이 소유한 숙소에 객실 등록을 할 수 있도록 기능을 구현해야 합니다. 

### 📜Todo
- [x] 객실 등록 기능 구현
- [x] 객실 등록 기능 테스트 작성
- [x] 객실 등록 API Docs 작성
