### ISSUE TITLE
issue: 객실 목록/상세 정보 조회 기능 개발

### ISSUE THREAD

**Issue by JeongUijeong** [Upjuyanolja/Upjuyanolja_BE#68]
### 💬Description
업주 회원이 보유한 숙소에 등록된 객실 목록과 객실 상세 정보를 조회할 수 있도록 기능을 개발해야 합니다. 

### 📜Todo
- [x] 객실 목록 조회 기능 구현
- [x] 객실 목록 조회 기능 테스트 코드 작성
- [x] 객실 상세 조회 기능 구현
- [x] 객실 상세 조회 기능 테스트 코드 작성
- [x] 객실 목록 조회, 상세 조회 API Docs 작성
