### ISSUE TITLE
issue: 객실 수정 기능 개발

### ISSUE THREAD

**Issue by JeongUijeong** [Upjuyanolja/Upjuyanolja_BE#79]
### 💬Description
업주 회원이 소유한 숙소의 객실 정보를 수정할 수 있도록 객실 수정 기능을 개발합니다. 

### 📜Todo
- [x] 객실 수정 기능 개발
- [x] 객실 수정 기능 테스트 작성
- [x] 객실 수정 API Docs 테스트 + adoc 작성
