### ISSUE TITLE
issue: 객실 삭제 기능 개발

### ISSUE THREAD

**Issue by JeongUijeong** [Upjuyanolja/Upjuyanolja_BE#80]
### 💬Description
업주 회원이 소유한 숙소의 객실을 삭제할 수 있도록 객실 삭제 기능을 개발합니다. 

### 📜Todo
- [x] 객실 삭제 기능 구현
- [x] 객실 삭제 기능 테스트 작성
- [x] 객실 삭제 API Docs 테스트 + adoc 작성
