### ISSUE TITLE
issue: 오픈 API로 받아온 숙소 소유권/카테고리 설정

### ISSUE THREAD

**Issue by JeongUijeong** [Upjuyanolja/Upjuyanolja_BE#85]
### 💬Description
기획팀과 논의한 대로 오픈 API에서 받아온 숙소 데이터들은 임의로 초기에 생성한 업주 회원의 소유로 설정합니다. 
카테고리는 논의를 통해 정해 아래와 같이 설정합니다. 

// 호텔/리조트
HOTEL("호텔")
RESORT("리조트)
TOURIST_HOTEL("관광호텔")
CONDO("콘도")
RESIDENCE("레지던스")

// 모텔
MOTEL("모텔")

// 펜션/풀빌라
PENSION_POOL_VILLA("펜션/풀빌라")

// 게스트하우스
GUEST_HOUSE("게스트하우스")
HANOK("한옥")

### 📜Todo
- [x] 업주 회원 생성 로직 추가
- [x] 소유권 설정 로직 추가
- [x] 숙소 카테고리 설정 로직 추가
