### ISSUE TITLE
issue: 쿠폰 만들기(View Data) 기능 개발

### ISSUE THREAD

**Issue by matrixpower1004** [Upjuyanolja/Upjuyanolja_BE#86]
## 🛠️
쿠폰 만들기(View Data) 기능을 개발한다.

### 💬Description
쿠폰 만들기 화면에 필요한 데이터들을 View에 응답하는 기능을 개발한다.

### 📜Todo
- [x] Repository 구현 및 테스트 작성
- [x] Service 구현
- [x] Controller 구현 및 테스트 작성
- [x] REST Doc 파일 생성
- [x] Coupon 관련 Entity Refactoring
