### ISSUE TITLE
issue: 쿠폰 만들기 기능 개발

### ISSUE THREAD

**Issue by matrixpower1004** [Upjuyanolja/Upjuyanolja_BE#94]
### 💬Description
- 쿠폰의 만들기 기능을 개발한다.
- 같은 숙소에 같은 정액/정률 쿠폰이 존재하면 수량을 증가시킨다.

### 📜Todo
- [x] 쿠폰 만들기 기능 구현
- [ ] 쿠폰 만들기 테스트 작성
- [ ] 쿠폰 만들기 REST Docs 작성
